"""WRONG LOCATION — this file is a stub.

The canonical fig6 script is at:
  Fedlearn/manuscript/figure_scripts/fig6_e6_fairness.py

This path (trust-ct/manuscript/figure_scripts/) resolves ROOT incorrectly
and was written here by mistake.  Do not edit this file.
"""
raise RuntimeError(
    "Wrong location. Run Fedlearn/manuscript/figure_scripts/fig6_e6_fairness.py instead."
)
